steps:   
    # build the app image
    - name: 'eu.gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'eu.gcr.io/krisenheldinnen', '.']

# image is pushed to Container Registry
images:
- 'eu.gcr.io/krisenheldinnen'