# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Address(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, street: str=None, house_number: str=None, postal_code: str=None, state: str=None):  # noqa: E501
        """Address - a model defined in Swagger

        :param street: The street of this Address.  # noqa: E501
        :type street: str
        :param house_number: The house_number of this Address.  # noqa: E501
        :type house_number: str
        :param postal_code: The postal_code of this Address.  # noqa: E501
        :type postal_code: str
        :param state: The state of this Address.  # noqa: E501
        :type state: str
        """
        self.swagger_types = {
            'street': str,
            'house_number': str,
            'postal_code': str,
            'state': str
        }

        self.attribute_map = {
            'street': 'street',
            'house_number': 'houseNumber',
            'postal_code': 'postalCode',
            'state': 'state'
        }
        self._street = street
        self._house_number = house_number
        self._postal_code = postal_code
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def street(self) -> str:
        """Gets the street of this Address.


        :return: The street of this Address.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this Address.


        :param street: The street of this Address.
        :type street: str
        """

        self._street = street

    @property
    def house_number(self) -> str:
        """Gets the house_number of this Address.


        :return: The house_number of this Address.
        :rtype: str
        """
        return self._house_number

    @house_number.setter
    def house_number(self, house_number: str):
        """Sets the house_number of this Address.


        :param house_number: The house_number of this Address.
        :type house_number: str
        """

        self._house_number = house_number

    @property
    def postal_code(self) -> str:
        """Gets the postal_code of this Address.


        :return: The postal_code of this Address.
        :rtype: str
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code: str):
        """Sets the postal_code of this Address.


        :param postal_code: The postal_code of this Address.
        :type postal_code: str
        """

        self._postal_code = postal_code

    @property
    def state(self) -> str:
        """Gets the state of this Address.


        :return: The state of this Address.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Address.


        :param state: The state of this Address.
        :type state: str
        """

        self._state = state
