# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Contract(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, job_application_id: str=None, employer_signed: str=None, employee_signed: str=None):  # noqa: E501
        """Contract - a model defined in Swagger

        :param id: The id of this Contract.  # noqa: E501
        :type id: str
        :param job_application_id: The job_application_id of this Contract.  # noqa: E501
        :type job_application_id: str
        :param employer_signed: The employer_signed of this Contract.  # noqa: E501
        :type employer_signed: str
        :param employee_signed: The employee_signed of this Contract.  # noqa: E501
        :type employee_signed: str
        """
        self.swagger_types = {
            'id': str,
            'job_application_id': str,
            'employer_signed': str,
            'employee_signed': str
        }

        self.attribute_map = {
            'id': 'id',
            'job_application_id': 'jobApplicationId',
            'employer_signed': 'employerSigned',
            'employee_signed': 'employeeSigned'
        }
        self._id = id
        self._job_application_id = job_application_id
        self._employer_signed = employer_signed
        self._employee_signed = employee_signed

    @classmethod
    def from_dict(cls, dikt) -> 'Contract':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The contract of this Contract.  # noqa: E501
        :rtype: Contract
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Contract.


        :return: The id of this Contract.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Contract.


        :param id: The id of this Contract.
        :type id: str
        """

        self._id = id

    @property
    def job_application_id(self) -> str:
        """Gets the job_application_id of this Contract.


        :return: The job_application_id of this Contract.
        :rtype: str
        """
        return self._job_application_id

    @job_application_id.setter
    def job_application_id(self, job_application_id: str):
        """Sets the job_application_id of this Contract.


        :param job_application_id: The job_application_id of this Contract.
        :type job_application_id: str
        """

        self._job_application_id = job_application_id

    @property
    def employer_signed(self) -> str:
        """Gets the employer_signed of this Contract.


        :return: The employer_signed of this Contract.
        :rtype: str
        """
        return self._employer_signed

    @employer_signed.setter
    def employer_signed(self, employer_signed: str):
        """Sets the employer_signed of this Contract.


        :param employer_signed: The employer_signed of this Contract.
        :type employer_signed: str
        """

        self._employer_signed = employer_signed

    @property
    def employee_signed(self) -> str:
        """Gets the employee_signed of this Contract.


        :return: The employee_signed of this Contract.
        :rtype: str
        """
        return self._employee_signed

    @employee_signed.setter
    def employee_signed(self, employee_signed: str):
        """Sets the employee_signed of this Contract.


        :param employee_signed: The employee_signed of this Contract.
        :type employee_signed: str
        """

        self._employee_signed = employee_signed
