# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Picture(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, document_type: str=None, path: str=None):  # noqa: E501
        """Picture - a model defined in Swagger

        :param document_type: The document_type of this Picture.  # noqa: E501
        :type document_type: str
        :param path: The path of this Picture.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'document_type': str,
            'path': str
        }

        self.attribute_map = {
            'document_type': 'documentType',
            'path': 'path'
        }
        self._document_type = document_type
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'Picture':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The picture of this Picture.  # noqa: E501
        :rtype: Picture
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_type(self) -> str:
        """Gets the document_type of this Picture.


        :return: The document_type of this Picture.
        :rtype: str
        """
        return self._document_type

    @document_type.setter
    def document_type(self, document_type: str):
        """Sets the document_type of this Picture.


        :param document_type: The document_type of this Picture.
        :type document_type: str
        """

        self._document_type = document_type

    @property
    def path(self) -> str:
        """Gets the path of this Picture.


        :return: The path of this Picture.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this Picture.


        :param path: The path of this Picture.
        :type path: str
        """

        self._path = path
